// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3acooB5YHAtystGoswoxpyx_Txi8dUE',
    appId: '1:843130018970:android:a55e7243ccd815b633d323',
    messagingSenderId: '843130018970',
    projectId: 'expense-tracker-8769a',
    storageBucket: 'expense-tracker-8769a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiW1LdH7ZX1b0FNUTo-oneJ8yGsJ6VUGk',
    appId: '1:843130018970:ios:ee0a9eb991d377c333d323',
    messagingSenderId: '843130018970',
    projectId: 'expense-tracker-8769a',
    storageBucket: 'expense-tracker-8769a.appspot.com',
    androidClientId: '843130018970-acni0q1jrdr7voup2j8882ec5trtn6ne.apps.googleusercontent.com',
    iosClientId: '843130018970-5l6dq58nqqm1srqqjb14i5ags2nnbdmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
